// <auto-generated />
namespace PghTechFest.Www.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class scheduleshit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scheduleshit));
        
        string IMigrationMetadata.Id
        {
            get { return "201504291258423_schedule-shit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
